---
apiVersion: v1
kind: Namespace
metadata:
  name: curlme-controller
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: curlme
  namespace: curlme-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: curlme
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["update", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: curlme
subjects:
  - kind: ServiceAccount
    name: curlme
    namespace: curlme-controller
roleRef:
  kind: ClusterRole
  name: curlme
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curlme
  namespace: curlme-controller
  labels:
    app: curlme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curlme
  template:
    metadata:
      labels:
        app: curlme
    spec:
      serviceAccountName: curlme
      containers:
        - name: curlme
          image: etiennecoutaud/curlme-controller:latest
          ports:
          - containerPort: 9100
            name: metrics