---
apiVersion: v1
kind: Service
metadata:
  name: curlme-metrics
  labels:
    svc: curlme-metrics
spec:
  ports:
    - name: metrics
      port: 9100
      targetPort: metrics
      protocol: TCP
  selector:
    app: curlme
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: curlme-exporter
spec:
  endpoints:
    - interval: 30s
      port: metrics
  jobLabel: svc
  namespaceSelector:
    matchNames:
      - curlme-controller
  selector:
    matchLabels:
      svc: curlme-metrics
